---
title: "Final"
author: "Amanda Stedman"
date: "12/6/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 10

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)

d = read_csv('diamonds.csv')
d <- d %>% select(-id)
variables_names = names(d)
variables_numeric = d %>% select_if(is.numeric) %>% names
variables_category = d %>% select_if(is.character) %>% names
ui <- fluidPage(
  
  titlePanel("Density Plot for Diamonds Data"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variable",
        choices = variables_numeric, selected = "price"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variable",
        choices = variables_category,
        selected = "shape"
      ),
      
      checkboxGroupInput(inputId = "color", label = "Select Color",
                         choices = names(table(d$color)), inline = TRUE),
      
      sliderInput(inputId = "carat",
                  "Select Carat Range:",
                  min = min(d$carat, na.rm=TRUE),
                  max = max(d$carat, na.rm=TRUE),
                  value= c(.2, 3.1)), 
    
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Density Plot" = "density",
                               "Histogram Plot" = "histogram"),
                   selected = 'density')
      
    ),
    
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    color = input$color
    
    
    library(ggplot2)
    d <- d %>% filter(carat>input$carat[1], carat<input$carat[2])
    d <- d %>% filter(color %in% input$color)
    if(input$plot_choice == 'density')
      
    {
      ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_density()+
        labs(x = v1, color = v2)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_histogram()+
        labs(x = v1, color = v2)
    }
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

## Question 11

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)

d = read_csv('diamonds.csv')
d <- d %>% select(-id)
variables_names = names(d)
variables_numeric = d %>% select_if(is.numeric) %>% names
variables_category = d %>% select_if(is.character) %>% names
ui <- fluidPage(
  
  titlePanel("Density Plot for Diamonds Data"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variable",
        choices = variables_numeric, selected = "price"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variable",
        choices = variables_category,
        selected = "shape"
      ),
      
      checkboxGroupInput(inputId = "color", label = "Select Color",
                         choices = names(table(d$color)), inline = TRUE),
      
      dateRangeInput(inputId = "date", 
                     strong("Date range"), 
                     start = "2009-10-10", end = "2019-03-02",
                     min = "2009-10-10", max = "2019-03-02"), 
    
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Density Plot" = "density",
                               "Histogram Plot" = "histogram"),
                   selected = 'density')
      
    ),
    
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    color = input$color
    print(v1)
    
    
    library(ggplot2)
    d <- d %>% filter(date>input$date[1], date<input$date[2])
    d <- d %>% filter(color %in% input$color)
    if(input$plot_choice == 'density')
      
    {
      ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_density()+
        labs(x = v1, color = v2)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_histogram()+
        labs(x = v1, color = v2)
    }
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

## Question 12

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)

d = read_csv('diamonds.csv')
d <- d %>% select(-id)
variables_names = names(d)
variables_numeric = d %>% select_if(is.numeric) %>% names
variables_category = d %>% select_if(is.character) %>% names
ui <- ui <- navbarPage("Navbar!",
                       tabPanel("Plot1",
                                
                                sidebarLayout(
                                  sidebarPanel(
                                    
                                    selectInput(
                                      inputId ="var1",
                                      label = "Select a Numeric Variable",
                                      choices = variables_names, selected = "price"),
                                    checkboxGroupInput(inputId = "color", label = "Select Color",
                                                       choices = names(table(d$color)), inline = TRUE),
                                    radioButtons(inputId = "plot_choice", 
                                                 label = h3("Select Plot:"),
                                                 choices = c("Density Plot" = "density",
                                                             "Histogram Plot" = "histogram"),
                                                 selected = 'density'),
                                    sliderInput(inputId = "carat",
                                                "Select Carat Range:",
                                                min = min(d$carat, na.rm=TRUE),
                                                max = max(d$carat, na.rm=TRUE),
                                                value= c(.2, 3.1)
                                    )
                                  ),
                                  
                                  mainPanel(
                                    plotOutput(outputId = 'show_plot')
                                  )
                                )
                       ),
                       
                       
                       tabPanel("Plot2",
                                
                                sidebarLayout(
                                  sidebarPanel(
                                    
                                    selectInput(
                                      inputId ="var2",
                                      label = "Select a Categorical Variable",
                                      choices = variables_names, selected = "shape"),
                                    
            
                                    sliderInput(inputId = "carat",
                                                  "Select Carat Range:",
                                                  min = min(d$carat, na.rm=TRUE),
                                                  max = max(d$carat, na.rm=TRUE),
                                                  value= c(.2, 3.1)
                                    )
                                  ),
                                  
                                  mainPanel(
                                    plotOutput(outputId = 'show_plot2')
                                  )
                                )
                       )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    color = input$color
    print(v1)
    
    library(ggplot2)
    d <- d %>% filter(carat>input$carat[1], carat<input$carat[2])
    d <- d %>% filter(color %in% input$color)
    if(input$plot_choice == 'density')
    {
    ggplot(d, aes(x = d[[v1]]))+
      geom_density()+
      labs(x = v1)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]]))+
        geom_histogram()+
        labs(x = v1)
    }
    
    
  })

  
  output$show_plot2 <- renderPlot({
    
    v2 = input$var2
    color = input$color
    
    library(ggplot2)
    d <- d %>% filter(carat>input$carat[1], carat<input$carat[2])
    ggplot(d, aes(x = d[[v2]]))+
      geom_bar()+
      labs(x = v2)
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

